services:
  # === FRONTEND ===
  - type: web
    env: static
    name: heistgame-frontend
    plan: free
    rootDir: "HeistGAME Frontend"
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: NODE_VERSION
        value: 20

  # === BACKEND ===
  - type: web
    name: heistgame-backend
    plan: free
    region: singapore
    runtime: docker
    dockerContext: ./HeistGAME
    dockerfilePath: ./HeistGAME/Dockerfile
    envVars:
      - key: DATABASE_URL
        fromService:
          type: redis
          name: heistgame-db
          property: connectionString

  # === VALKEY (REDIS) ===
  - type: redis
    name: heistgame-db
    plan: free
    region: singapore
    ipAllowList: []
