services:
  # === FRONTEND ===
  - type: static_site
    name: heistgame-frontend
    rootDir: "HeistGAME Frontend"
    buildCommand: npm install && npm run build
    publishPath: dist
    envVars:
      - key: NODE_VERSION
        value: 20

  # === BACKEND ===
  - type: web
    name: heistgame-backend
    runtime: docker
    dockerContext: ./HeistGAME
    dockerfilePath: ./HeistGAME/Dockerfile
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: DATABASE_URL
        fromService:
          type: redis
          name: heistgame-db
          property: connectionString

  # === VALKEY (REDIS) ===
  - type: redis
    name: heistgame-db
    ipAllowList: []
