services:
  - type: redis
    name: valkey-db
    region: singapore
    plan: free
    ipAllowList: []

  - type: web
    name: art-heist-backend
    runtime: docker
    region: singapore
    plan: free
    dockerfilePath: ./HeistGAME/Dockerfile
    dockerContext: ./HeistGAME
    healthCheckPath: /test-cors
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: VALKEY_HOST
        fromService:
          type: redis
          name: valkey-db
          property: host
      - key: VALKEY_PORT
        fromService:
          type: redis
          name: valkey-db
          property: port
      - key: FRONTEND_URL
        fromService:
          type: web
          name: art-heist-frontend
          property: url

  - type: web
    name: art-heist-frontend
    runtime: static
    region: global
    plan: free
    rootDir: "./HeistGAME Frontend"
    buildCommand: npm install && npm run build
    publishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: art-heist-backend
          property: url
